language: go

sudo: false

go:
- "1.11.x"

git:
  depth: 1

install:
- export GO111MODULE=on
- go mod download
- go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
- go build -o ./exalysis cmd/exalysis/*.go
- go test -cover -tags=testing ./...
